### PR TITLE
add package: the Tractor

### PR DESCRIPTION
**Pull request by dstndstn**
Hi Ted,
You may be busy with DESI CD2, but if not, any chance you could merge & install this on carver & edison?  This is the code we're using for reducing the DECam Legacy Survey.  We have pulled out our more-rapidly-changing driver code, so this package should require fewer updates.  A few collaborators are interested in using the code, so it's handy to be able to have it built at NERSC.  But I also understand if you want to keep HPCPorts more general-purpose.
Thanks,
--dstn

### CODE REVIEW

**Comment by sbailey** [comment]
FWIW, I recommend keeping HPCports as more general cross-project support code, and install project-specific code in project-specific areas.  In the case of Tractor, either cosmo or desi would be fine areas to install it at NERSC.  It feels like feature creep to include codes like Tractor in HPCports itself, and could add up to long term maintenance burden if N>>1 codes like Tractor get added.

**Comment by tskisner** [comment]
I don't mind ~monthly updates to packages, especially if Dustin is 
willing to update the package file himself.  But I agree we should be 
mindful of the target audience of packages...

**Comment by rcthomas** [comment]
I don't think this is a feature creep --- Tractor is an independent open source code like SExtractor or Astrometry.net, and if "either cosmo or desi would be fine" that suggests HPCports is the best answer.  If would be like putting synapps under either SNfactory or PTF --- people outside that repo wanted to use it, so I asked to have it put under HPCports.

**Comment by dstndstn** [comment]
So, another tack would be to try to make it easier for developers to maintain their own hpcports "overlay" installations.  Perhaps modify HPCP_PREFIX to be a colon-separated list of paths to check, so that as an ordinary Joe, I can build the tractor package in my own ~/HPCP directory, but all other packages are pulled from the usual system repository.  This would then make it not Ted's problem to build and install new package versions.  Perhaps the tractor package could go in a new place for "obscure" or "probationary" packages that are not built in the normal course of things, but are still available as hpcports recipes.

Oh, I see you just merged it.  Thanks!

**Comment by tskisner** [comment]
yes, there are other packages already in hpcports that are waaay more 
project-specific than tractor.

Ideally we would instead get conda playing well with Cray compilers and 
then have build recipes for all our packages.  Then we could have a cron 
job build everything once a week on each machine and upload the binaries 
to binstar.  Then people could have complete control over which packages 
they had installed in their environment and pull over pre-built binaries 
for most things.

Ah, someday...

-T

**Comment by sbailey** [comment]
I've been outvoted which is fine, but for the record — the specific scenario I'm concerned about is something like this: NERSC updates the Cori OS and Cray compilers, triggering a rebuild of everything in HPCports for a new release.  If a fairly project-specific package like Tractor breaks, it should be Dustin's problem to fix it, not Ted's, and it shouldn't hold up a release of an otherwise self consistent HPCports build (perhaps it wouldn't anyway).  There will always been gray areas as to what is "project specific" code, but there should be some caution applied before accepting new packages, based upon the impact of who has to fix it and what gets delayed if it breaks in a future compiler upgrade.  Perhaps this is a non-issue if breaking a dependency-leaf-level package doesn't hold up an HPCports release or take up Ted's time.

**Comment by tskisner** [comment]
This sort of thing actually has happened in the past with other 
packages.  Typically I just leave the broken package uninstalled until 
someone complains and offers to fix it or pay me to fix it ;-)

-Ted

**Comment by rcthomas** [comment]
I have observed that Ted is likely to fix *build* problems that pop up in HPCports packages like all the time.  Beyond that, if there's something in the upstream codebase that is no longer valid because of something changing in the OS or toolchain or whatevez, it depends on how many lines of code it is.  Like, he'll fix a dropped include, but beyond that he emails you to say "your thingie's borked."  Ted is so cool.

**Pull request merged**
