### PR TITLE
add Astrometry.net

### PR DESCRIPTION
**Pull request by dstndstn**
With python bindings, but without cairo-dependent stuff.

### CODE REVIEW

**Comment by dstndstn** [comment]
Oh, wait, hang on, the installed module doesn't work:

> module load astrometry.net-hpcp
-bash: astrometry.net_PREFIX=/global/homes/d/dstn/HPCP/astrometry.net-0.52_1ec08a28-1.0: No such file or directory
-bash: export: `astrometry.net_PREFIX': not a valid identifier
-bash: astrometry.net_VERSION=0.52_1ec08a28-1.0: command not found
-bash: export: `astrometry.net_VERSION': not a valid identifier


Guess I need to call it astrometry_net or something?

**Comment by dstndstn** [comment]
@tskisner , could you suggest the minimal number of places I have to change the name to get this going?  (Or, if you want fancy points, automatically turn . to _ when writing out the env*.sh file!)

**Comment by tskisner** [comment]
Using a "-" instead of a dot in the package directory and the PKG_NAME should be sufficient.

**Comment by weaverba137** [comment]
Just be careful that the "-" is not present in any environment variable.  Hyphens in environment variables are not good.

**Comment by tskisner** [comment]
Good point- you should use underscores.  There are 2 other packages that use underscores successfully.

**Comment by dstndstn** [comment]
This seems to be working now.

**Pull request merged**
